# avec sudo ansible-playbook -c local config.vm1.yml
---
- hosts: localhost
  tasks:
      # adresse IPv6 avec nmcli (CLI pour NetworkManager)
      # éventuellement, pour supprimer les connexions en trop, faire
      # $ nmcli connection del ansible-eth1
#   - shell: ip -6 route delete default
   - shell: nmcli connection add ifname eth1 con-name eth1-LAN3 type ethernet ip4 172.16.2.156/28
   - shell: nmcli connection add ifname eth2 con-name eth2-LAN1-6 type ethernet ip6 fc00:1234:1::16/64
   - shell: ip route delete default
     ignore_errors: True
   - shell: ip route delete default
     ignore_errors: True
   - shell: ip route delete default
     ignore_errors: True
   - shell: ip route delete default
     ignore_errors: True
   - shell: ip -6 route delete default
     ignore_errors: True
   - shell: ip -6 route delete default
     ignore_errors: True
   - shell: ip -6 route delete default
     ignore_errors: True
   - shell: ip -6 route delete default
     ignore_errors: True
   - shell: ip route add 172.16.2.128/28 via 172.16.2.151 dev eth1  #-->LAN1
   - shell: ip route add 172.16.2.160/28 via 172.16.2.151 dev eth1  #-->LAN2
#   - shell: ip route add 172.16.2.144/28 dev eth1                   #-->LAN3
   - shell: ip route add 172.16.2.176/28 via 172.16.2.151 dev eth1  #-->LAN4  
#   - shell: ip -6 route add fc00:1234:1::/48 dev eth2               #-->LAN2-6
   - shell: ip -6 route add fc00:1234:2::/64 via fc00:1234:1::26 dev eth2 #-->LAN1-6
